# Generated by Django 4.2.4 on 2023-09-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonDRF', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='category',
            new_name='user',
        ),
    ]
